### ISSUE TITLE
JavaScript heap out of memory using validator-cli.js with custom schema (arrays). 

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/biovalidator#30]
### Summary
Executing Biovalidator using its CLI script (``validator-cli.js``) gets stalled and eventually throws a fatal error (``JavaScript heap out of memory``). 

## Description
I am trying to make use of the Biovalidator in the CLI using ``validator-cli.js`` to validate a JSON document against a custom schema (Draft 2019-09). It gets stalled around 30-60 seconds and finally exits with a fatal error. Not using a version of Node.js below v10 could be at fault (for what I've seen in some [posts](https://stackoverflow.com/a/59572966/16221290)). 
The command I use and its output is the following:
````
$ time node ./validator-cli.js -s schema.json -j json_doc.json

<--- Last few GCs --->

[1335:0x3dfcf90]    34692 ms: Scavenge 1377.0 (1421.2) -> 1375.5 (1422.2) MB, 2.4 / 0.0 ms  (average mu = 0.085, current mu = 0.001) allocation failure
[1335:0x3dfcf90]    34699 ms: Scavenge 1377.2 (1422.2) -> 1375.7 (1423.2) MB, 2.8 / 0.0 ms  (average mu = 0.085, current mu = 0.001) allocation failure
[1335:0x3dfcf90]    34705 ms: Scavenge 1377.5 (1423.2) -> 1375.9 (1429.2) MB, 2.5 / 0.0 ms  (average mu = 0.085, current mu = 0.001) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xee28515be1d]
    1: StubFrame [pc: 0xee2851134b0]
Security context: 0x390d8aa9e6e9 <JSObject>
    2: serialize [0xb6ee4d18999] [/mnt/c/Users/mcasado/Documents/GitHub/biovalidator/node_modules/uri-js/dist/es5/uri.all.js:~1001] [pc=0xee2855d04cd](this=0x0b6ee4d1bf31 <Object map = 0x1e7141271389>,components=0x15dc21bec709 <Object map = 0x22fff8fd149>)
    3: resolveSchema [0xb6ee4d1c0a9] [/mnt/c/Users/mcasado/Document...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa090 node::Abort() [node]
 2: 0x8fa0dc  [node]
 3: 0xb0052e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb00764 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef4c72  [node]
 6: 0xef4d78 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf00e52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf01784 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf043f1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xecd874 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x116d9fe v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0xee28515be1d
Aborted

real    0m35.526s
user    0m36.739s
sys     0m1.720s
````
The **JSON schema** (``schema.json``) is:
````
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "test_schema_X",
    "type": "object",
    "required": ["sample_labels"],
    "additionalProperties": false,
    "properties": {
      "sample_labels": {
        "type": "array",
        "minItems": 1,
        "additionalProperties": false,
        "items": {
          "type": "object",
          "required": ["label"],
          "additionalProperties": false,
          "properties": {
            "label": {
              "type": "string"
            } 
          }
        }
      }
    }  
}
````
And the **JSON document** (``json_doc.json``):
````
{
  "sample_labels": [
    {
      "label": "test1"
    },
    {
      "label": "test2"
    }
  ]
}
````
Even though it would not be a solution, I thought of increasing the memory dedicated to Node.js:
```
export NODE_OPTIONS="--max-old-space-size=8192"
```
The outcome is that instead of stalling for 30-60 seconds, the execution gets stalled for 4 minutes, but throws the same type of error. 
### AJV execution
When trying to validate the JSON document against its schema using AJV directly (its CLI feature ``ajv-cli``) it does work and validation is passed:
````
$ ajv --spec=draft2019 -s schema.json -d json_doc.json
strict mode: missing type "object" for keyword "additionalProperties" at "test_schema_X#/properties/sample_labels" (strictTypes)
json_doc.json valid
````
### Using validator-cli.js with other JSON schemas/documents and tests
Tests are passed correctly:
````
Test Suites: 10 passed, 10 total
Tests:       27 passed, 27 total
Snapshots:   0 total
Time:        48.545 s
Ran all test suites.
````

And using ``validator-cli.js`` with other schemas and documents seems to work:
````
$ time node ./validator-cli.js -s examples/schemas/test-schema.json -j examples/objects/test-schema-valid.json
 No validation errors reported.
Validation finished.

real    0m6.116s
user    0m0.867s
sys     0m0.571s

$ time node ./validator-cli.js -s examples/schemas/test-schema.json -j examples/objects/test-schema-invalid.json
 The validation process has found the following error(s):

 /characteristics.organism
        should have required property 'organism'
/characteristics.Organism
        should have required property 'Organism'
/characteristics.species
        should have required property 'species'
/characteristics.Species
        should have required property 'Species'
/characteristics
        should match some schema in anyOf

Validation finished.

real    0m6.076s
user    0m0.813s
sys     0m0.595s
````

Therefore, what I guess is that there has to be some node within my custom schema that leads to an excess of memory use, some kind of memory leak or infinite loop. My suggestion, given the short length of my custom schema is that it could be related to the way ``items`` are handled in arrays by Biovalidator. 
### SO and versions
I am using **Windows Subsystem for Linux 2** (WSL2), ajv-cli ``v5.0.0``, npm ``v6.13.4`` and nodejs details are:
````
$ node -p process.versions
{ http_parser: '2.9.3',
  node: '10.19.0',
  v8: '6.8.275.32-node.55',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.39.2',
  napi: '5',
  openssl: '1.1.1d',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019c' }
````

I also tried using the latest versions of npm (``v8.1.3``) and nodejs (``v16.13.0``) to no avail, since they threw similar errors as the ``v10.19.0``, except for the ``Security context`` that is solved with the latest versions.

**Comment by theisuru** [comment]
Hi @M-casado,

I checked with few samples, looks like the problem is related to the `$schema` version. If we use `"$schema": "http://json-schema.org/draft-07/schema#"`, the example works fine. But when we use `"$schema": "https://json-schema.org/draft/2019-09/schema"` heap error occurs.

I tried the same with `ajv-cli` as you suggested. It works fine if we provide the version as an argument (`--spec=draft2019`), but fails if we did not provide this. 
```
$ ajv validate -s heap_error_test_schema.json -d heap_error_test.json
schema heap_error_test_schema.json is invalid
error: no schema with key or ref "https://json-schema.org/draft/2019-09/schema"

$ ajv --spec=draft2019 -s -s heap_error_test_schema.json -d heap_error_test.json
strict mode: missing type "object" for keyword "additionalProperties" at "test_schema_X#/properties/sample_labels" (strictTypes)
heap_error_test.json valid
```

If we change the version to `draft--07`, `ajv-cli` also works without the version argument.

I will further check how we can avoid this error and update here.

**Comment by M-casado** [comment]
Hi @theisuru, thank you for taking a look at the problem. Since the last time I commented I have modified the schemas a bit (specially the troublesome arrays), so I'll have to check again if Biovalidator works this time with the new versions. 

Nevertheless, regarding the issue being solved using ``draft--07``, I'm afraid that probably does not solve our issue, since we do want to use the newer drafts and keep up to date with those changes they bring. 

I'll comment again once I check again how it works.

**Comment by theisuru** [comment]
To add little bit more to the context. New versions of `ajv` supporting drafts `2019-9` and up have implemented different import statments to optimize for speed. So by default it only supports `draft-7`. We have to explicitly ask for later draft support. It is explained here in the [documentation](https://ajv.js.org/guide/schema-language.html). 

We will implment this in our next release.

**Comment by M-casado** [comment]
Using the branch from this PR https://github.com/elixir-europe/biovalidator/pull/32 I have checked again the same JSON schema and document. This time, since installing Biovalidator with the newest versions of Nodejs (16+) gave me troubles, I installed it with **Nodejs version ``12.0.0``** (lower versions did not work well with ``nodeenv``) and **npm version ``6.9.0``**. 

It did work as expected this time:
````
$ time node ./validator-cli.js -s test_schema.json -j test_json.json
 No validation errors reported.
Validation finished.

real    0m6.717s
user    0m0.776s
sys     0m1.087s
````
