### ISSUE TITLE
File-resolvable references (context for $id and $ref)

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/biovalidator#33]
## Summary

To be able to provide Biovalidator with filepaths to resolve references between JSON files. 

## Description

When building complex schemas it is common to reference inherited subschemas between JSON files through ``$id`` and ``$ref``. Currently I don't think there is a way for Biovalidator to accept filepaths of JSON files that contain such ``$id``s mentioned elsewhere. This is truly useful when running a JSON validator locally and when handling static references to files with different versions (e.g. ``"$id": "my-file.txt"`` existing in different versions of ``my-file.txt``). Besides, although ``$id``s are suggested to be URL-resolvable, this is just a recommendation, and thus it should not be expected for ``$id``s to always point to the correct JSON files. 

[**AJV-cli**](https://github.com/ajv-validator/ajv-cli) already allows for this to be done through the ``-r`` argument ([**referenced schemas**](https://github.com/ajv-validator/ajv-cli#-r---referenced-schemas)). This allows for the whole set of schemas to be passed to the validator. As an example:
````bash
schema_name="object-set"
json_doc="object-set-valid-1.json"
ajv --spec=draft2019 -s schemas/EGA.$schema_name.json -d schemas/validation_tests/$json_doc -r "schemas/EGA.!($schema_name).json"
````

**Comment by M-casado** [comment]
Hi @theisuru, sorry to bother you again, but I was curious if this feature is still planned or is otherwise discarded.

**Comment by theisuru** [comment]
hi @M-casado 
we can think of resloving given refrence using URI schemas. Example in your case would be passing `$ref` as `file://~/schemas/EGA/test.json`. Would that be sufficient? or are you looking for an option to specify a default schema in general.

**Comment by M-casado** [comment]
Hi again @theisuru! Sorry for the late answer. 

Actually in our use-case I've been specifying URIs for our ``$id`` parameters, so they are already pointing to a file, but in our case to a GitHub file. See [this](https://github.com/EbiEga/ega-metadata-schema/blob/12fb1cc53b297db215fd446f663f79bfebd9bf03/schemas/EGA.DAC.json#L76-L85), for example:
````
# Current example of a reference:
"$ref": "https://github.com/EbiEga/ega-metadata-schema/tree/main/schemas/EGA.common-definitions.json#/definitions/relationship_object
# Raw file in GH:
https://raw.githubusercontent.com/EbiEga/ega-metadata-schema/main/schemas/EGA.common-definitions.json
````
They point to the main GitHub repo, instead of the raw files, per se. If Biovalidator is able to pick the text files from those links, problem solved I would say. If not, . But going from ``https://github.com/...`` to ``https://raw.githubusercontent.com/...`` and getting rid of the ``tree`` in the middle is probably easy when parsing the schemas. Either that, or we could change the whole set of ``$ids`` if applicable.

I would love for this to get inertia, since we will soon start to actively seek ontology validation in our metadata validation. If possible, I would love to use Biovalidator instead of re-inventing the wheel. Would you be kind enough to meet soon with me and perhaps EGA developers to go over the possible course of action?

**Comment by theisuru** [comment]
@M-casado,
Happy to have a talk about this. Tony also recently mentined about the importance of having shared tools between our teams. So it will be possible to allocate time for this. We can prepare a set of goals and timeline for the biovalidator. Please feel free to schedule a meeting. Me and Dipayan in our team can come.

**Comment by M-casado** [comment]
@theisuru I just created a Polly. Everybody is welcomed, but I mainly expect you, Dipayan, an EGA developer and myself. We could highlight:

- EGA use case (pre-submission toolkit, remote validation, schemas structure...)
- How to contribute to Biovalidator (create issues, forks or even PRs?...)
- How to set up Biovalidator as a server (possible remote validation for the future)

**Comment by theisuru** [comment]
Hi @M-casado, I have pushed "referenced schema" change to the branch [support_local_schema_directory](https://github.com/elixir-europe/biovalidator/tree/support_local_schema_directory). I will add documentation soon. For now: similar to `ajv-cli`, this is supporting glob patterns. You can also provide directory or a file name.

```
 node ./validator-cli.js --schema=./test/resources/ref_test_schema.json --json=./test/resources/ref_test_valid.json --ref=./test/resources/schema_dir
```

**Comment by M-casado** [comment]
Hi @theisuru. I finally got my hands on the tool, and I'm very happy to confirm that it works as intended. I have yet to test it thoroughly, with validation corner cases, errors, etc. but based on some light testing it looks great.

### Specs
* **OS**: Windows 10 with Windows Subsystem for Linux 2 (WSL2). 
* **Node**: v16.13.0
* **npm**: 8.6.0

Started from scratch with the installation of Biovalidator. Went well and just had to fix some vulnerabilities (automatically done with ``npm audit fix``). 

## File references (through CLI)
I tested different combinations of JSON object validations against schemas that referenced each other (see real ``time`` next to each test):
- [ ] Empty JSON validation, with no references ``[0m5.722s]``
- [ ] ``[______]``
- [ ] ``[______]``
- [ ] ``[______]``
- [ ] ``[______]``
- [ ] ``[______]``

**Comment by M-casado** [comment]
Tested the references given when deploying the server and it works. These changes are currently within the ``dev`` branch. As soon as it is merged, I think this ticket can be closed.

Example of the command:
````
node src/biovalidator.js --ref=schemas/*.json --ref=schemas/controlled_vocabulary_schemas/*
````
