### ISSUE TITLE
[Server] Validation request hangs if the reference cannot be resolved

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/biovalidator#39]
### Summary
Testing Biovalidator server tool I noticed that if I use a reference (``$ref``) that is not given as a local reference when deploying the server (``--ref="..."``), the Post request just hangs there unresponsive, even though it was invalid from the server's perspective. 

By un-resolved reference I believe anything that is not plain text behaves the same: from GitHub URIs (not raw files) to pictures.

### Technical details:

- Testing deployment of the local server (localhost).
- Testing on current ``dev`` branch.
- Using ``curl`` to create the Post request.
- Using Windows Subsystem for Linux 2 (WSL2).
- Using Node ``v16.13.0`` and npm ``8.6.0``.

### Example

For example, starting the server as:
````
node ../../src/biovalidator.js
2022-06-13T17:22:39.933Z [info] ---------------------------------------------
2022-06-13T17:22:39.934Z [info] ------------ ELIXIR biovalidator ------------
2022-06-13T17:22:39.934Z [info] ---------------------------------------------
2022-06-13T17:22:39.934Z [info] Started server on port 3020 with base URL /
2022-06-13T17:22:39.935Z [info] PID file is available at ./server.pid
````
And the following ``data``:
````
{
    "schema": {
        "$ref": "https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png#/properties/object_title"
    },
    "data": {
        "test": "test"
    }
}
````
I received in the terminal where I deployed the server the following message:
````
2022-06-13T17:16:12.062Z [error] Failed to retrieve remote schema: https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png, TypeError: undefined
````
But I received nothing on the terminal executing the ``curl`` command (the process doesn't finish), nor it appeared in the logs created by the server.

**Comment by theisuru** [comment]
Good catch:
I am thinking, would that be a privacy problem if I log the error mesage with failed `$ref`. We will definitely send this to the uer though. Log would look like something below. 
```
Failed to retrieve remote schema: https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png
```

**Comment by M-casado** [comment]
Hi @theisuru! Sorry for the late response.
I think it would not be a privacy problem, since the schemas they reference should be ours. And in case they messed it and reference others, the ``$ref`` is intended to be used to reference other JSON schemas. Even in the worst case scenario, where their schemas were intended to be private, it would fail as it would not be able to retrieve them.

So yes, I think it's a good idea to log it. But besides the pointer or URL, I would also log in which schema this error appeared. So something like:
````
Error at schema X. Failed to retrieve remote schema: https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png
````
