### ISSUE TITLE
[Enhancement] Increasing the information of log files

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/biovalidator#43]
As far as I know, the current way logs are populated for a deployed server is by adding a line for each error that it encounters during validation. There are two enhancements I would like to propose:

1. Logs should also contain errorless validation attempts. This would improve the traceability of the issues and also improve the overall value of the logs, being able to weigh the erroneous attempts (e.g. ``We see that X% of the total was erroneous, due to this reason...``).
2. Logs should also contain information of the validation attempts performed through the User Interface (e.g. ``http://localhost:3020/`` in localhost). For what I've seen, the logs only contain attempts done through the Post requests, but not by the UI.

**Comment by theisuru** [comment]
1. This is now available in `dev` branch. Now we log each request with time it took to process. 
2. These logs should be available as UI also uses POST API. Let me know if this is not the case.

**Comment by M-casado** [comment]
Awesome, I was very interested in having the (1). 
Regarding (2), I haven't checked recently, but in the past I think we saw that the attempts were not being logged. Now, it's also true that the server instance failed from time to time, and accessing wrongly the UI crashed it some times. So perhaps that's why I couldn't see those attempts.
