### ISSUE TITLE
[Bug][Documentation] Improved bug report for existing PID files

### ISSUE THREAD

**Issue by M-casado** [elixir-europe/biovalidator#44]
### Summary
When a server is cut abruptly and the PID file is not removed, the re-deployment is blocked due to the existing PID file.

### Technical details

- Testing deployment of server.
- Testing on current dev branch.
- Using the UI and curl to create the Post requests.
- Using Windows Subsystem for Linux 2 (WSL2).
- Using Node ``v16.13.0`` and npm ``8.6.0``.

### Expected behaviour
When deploying a server with an already existing PID file in place, one of the following:

- It removes the existing PID file (a bit risky) and overwrites it with the new one.
- It informs you that the there is already a PID file with that filename and recommends you to remove it or change the new PID filename (``pidPath`` argument).

### Observed behaviour
It reports the following statement, without handling the issue correctly:
````bash
[winston] Unknown logger level: Failed to create PID file.
````
If the PID file is removed, it works.

### To reproduce

1. Have a PID file in place with the default filename (``server.pid``), either by stopping the tool abruptly or by creating it on your own.
2. Deploy the server (``node src/biovalidator.js``).
3. Observe printed message.

**Comment by theisuru** [comment]
More descriptive error message was added. This is available in `dev` branch now.
